[2023-12-25T11:21:23.291+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL.Post_to_Elasticsearch manual__2023-12-25T11:21:19.150376+00:00 [queued]>
[2023-12-25T11:21:23.296+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL.Post_to_Elasticsearch manual__2023-12-25T11:21:19.150376+00:00 [queued]>
[2023-12-25T11:21:23.296+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T11:21:23.297+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2023-12-25T11:21:23.297+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T11:21:23.303+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Post_to_Elasticsearch> on 2023-12-25 11:21:19.150376+00:00
[2023-12-25T11:21:23.310+0000] {standard_task_runner.py:52} INFO - Started process 240 to run task
[2023-12-25T11:21:23.312+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'Post_to_Elasticsearch', 'manual__2023-12-25T11:21:19.150376+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_saepul_hilal_DAG.py', '--cfg-path', '/tmp/tmp2gs1at7o', '--error-file', '/tmp/tmprm4jzr6y']
[2023-12-25T11:21:23.314+0000] {standard_task_runner.py:80} INFO - Job 19: Subtask Post_to_Elasticsearch
[2023-12-25T11:21:23.366+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL.Post_to_Elasticsearch manual__2023-12-25T11:21:19.150376+00:00 [running]> on host 0df44d59871b
[2023-12-25T11:21:23.405+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=saepul
AIRFLOW_CTX_DAG_ID=ETL
AIRFLOW_CTX_TASK_ID=Post_to_Elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2023-12-25T11:21:19.150376+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-25T11:21:19.150376+00:00
[2023-12-25T11:21:23.426+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/steps/push.py", line 23, in push_to_elastic
    res=es.index(index="milestone3_saepul_hilal_data_clean", document=doc)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: index() got an unexpected keyword argument 'document'
[2023-12-25T11:21:23.433+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL, task_id=Post_to_Elasticsearch, execution_date=20231225T112119, start_date=20231225T112123, end_date=20231225T112123
[2023-12-25T11:21:23.440+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task Post_to_Elasticsearch (index() got an unexpected keyword argument 'document'; 240)
[2023-12-25T11:21:23.448+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-25T11:21:23.477+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
