[2023-12-25T10:27:42.616+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL.Post_to_Elasticsearch manual__2023-12-25T10:17:35.996651+00:00 [queued]>
[2023-12-25T10:27:42.626+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL.Post_to_Elasticsearch manual__2023-12-25T10:17:35.996651+00:00 [queued]>
[2023-12-25T10:27:42.626+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T10:27:42.626+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 2
[2023-12-25T10:27:42.626+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-12-25T10:27:42.636+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Post_to_Elasticsearch> on 2023-12-25 10:17:35.996651+00:00
[2023-12-25T10:27:42.642+0000] {standard_task_runner.py:52} INFO - Started process 1117 to run task
[2023-12-25T10:27:42.646+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'Post_to_Elasticsearch', 'manual__2023-12-25T10:17:35.996651+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_saepul_hilal_DAG.py', '--cfg-path', '/tmp/tmp3neygdgi', '--error-file', '/tmp/tmp3dgb8ny3']
[2023-12-25T10:27:42.647+0000] {standard_task_runner.py:80} INFO - Job 14: Subtask Post_to_Elasticsearch
[2023-12-25T10:27:42.712+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL.Post_to_Elasticsearch manual__2023-12-25T10:17:35.996651+00:00 [running]> on host 0df44d59871b
[2023-12-25T10:27:42.766+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=saepul
AIRFLOW_CTX_DAG_ID=ETL
AIRFLOW_CTX_TASK_ID=Post_to_Elasticsearch
AIRFLOW_CTX_EXECUTION_DATE=2023-12-25T10:17:35.996651+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-25T10:17:35.996651+00:00
[2023-12-25T10:27:42.804+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/steps/push.py", line 23, in push_to_elastic
    res=es.index(index="milestone3_saepul_hilal_data_clean", document=doc)
  File "/home/airflow/.local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: index() got an unexpected keyword argument 'document'
[2023-12-25T10:27:42.812+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=ETL, task_id=Post_to_Elasticsearch, execution_date=20231225T101735, start_date=20231225T102742, end_date=20231225T102742
[2023-12-25T10:27:42.819+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task Post_to_Elasticsearch (index() got an unexpected keyword argument 'document'; 1117)
[2023-12-25T10:27:42.858+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-25T10:27:42.880+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
